# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ska-PKKk7s_HK_Rd5ZKbkpYAZzLaGmnN
"""

def Finder(a):
  flag =0
  
  for i in range(0,len(a)):
    if flag == 0 and (a[i] == 'F' or a[i] == 'S'):
      flag += 1
      posi = 0
    
    elif flag != 0 and a[i] == '.':
      posi += 1
    
    elif flag != 0 and (a[i] == 'F' or a[i] == 'S'):
      posi += 1
      break
  
  return posi

arr = "..F.....S..."
Finder(arr)
